name: Compare PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  compare-pr-to-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout `main` repository
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout PR repository
      uses: actions/checkout@v2
      with:
        path: pr

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run comparison script
      run: |
        python compare_pr_to_main.py --pr_path pr/changes/stable_diffusion/stable_diffusion.json --main_path main/stable_diffusion.json --main_hash ${{ github.event.pull_request.base.sha }} --pr_hash ${{ github.sha }} --output_dir changes/stable_diffusion/

    - name: Extract the first 8 characters from the main and PR hash and store them as variables
      run: |
        echo "MAIN_HASH=$(echo ${{ github.event.pull_request.base.sha }} | cut -c1-8)" >> "$GITHUB_ENV"
        echo "PR_HASH=$(echo ${{ github.sha }} | cut -c1-8)" >> "$GITHUB_ENV"

    - name: Check if output files are present
      run: |
        if [ ! -f changes/stable_diffusion/$MAIN_HASH...$PR_HASH/models_added.json ]; then
          echo "models_added.json is missing"
          exit 1
        fi
        if [ ! -f changes/stable_diffusion/$MAIN_HASH...$PR_HASH/models_removed.json ]; then
          echo "models_removed.json is missing"
          exit 1
        fi
        if [ ! -f changes/stable_diffusion/$MAIN_HASH...$PR_HASH/models_changed.json ]; then
          echo "models_changed.json is missing"
          exit 1
        fi
        
